### PR TITLE
Added support for iOS 13 Dark Mode

### PR DESCRIPTION
**Pull request by namannik**

### CODE REVIEW

**Comment by nfarina** [comment]
Hi, thanks for taking a stab at this! I tried it on my device and the default UI in "dark mode" doesn't really match the system very well:

Screen Shot 2019-09-26 at 11 45 24 AM

If you can adjust the callout graphics to match the system style more closely then I would be happy to merge.

**Comment by namannik** [comment]
Thanks for taking a look.  I'll get back to this in a few days and submit a new PR.

**Comment by namannik** [comment]
I've updated the pull request to better match the system style.  (It's not exact, but it's pretty close.)

One remaining issue is the border on `containerView` and `arrowView`.  On `containerView`, the border is visible behind the arrow.  On `arrowView`, there is no border.  Both of these views are now a `UIVisualEffectView`, and I haven't managed to figure out how to draw the arrow border without affecting its background color.

**Comment by namannik** [comment]
One more update: I switched to a different approach that doesn't use a `UIVisualEffectView`.  With this update, the border is now complete around the entire callout, including the arrow.

**Comment by nfarina** [comment]
Looks much better. Thanks so much for doing this!

**Pull request merged**
