### PR TITLE
modified this to more easily control the margin for the content view

### PR DESCRIPTION
**Pull request by vinnyt**
Need a finer grain way to control the margin on the callout view.

### CODE REVIEW

**Comment by rousseauo** [comment]
Great idea !

**Comment by nfarina** [comment]
This is a good idea; I've had to explain some silly tricks in the past to folks who wanted to adjust the margins. Perhaps this could be made into a property of the callout (separate properties for horizontal/vertical), and the corresponding constant could be eliminated?

**Comment by jszumski** [comment]
You should make the property a `UIEdgeInsets` to allow all 4 sides to be different.

**Comment by nfarina** [comment]
Oh duh, yes that's definitely the way to do it :)

**Comment by vinnyt** [comment]
I am sorry I didn't even think of the UIEdgeInsets,  @nfarina could you help me rework the main code to use the UIEdgeInsets?  I think I can update the delegate stuff.

**Comment by rousseauo** [comment]
PR #76 
I added a UIEdgeInsets property to set custom margin for the content view.

I also added an anchorHeight property in the SMBackgroundCalloutView. You can now set a custom SMBackgroundCalloutView with a custom arrow and set its height to have a good callout height.

**Comment by nfarina** [comment]
Hey guys, I've just merged #76 which supports this feature. Thanks so much for the contribution!

**Pull request closed without merging**
